# Generated by Django 6.0.3 on 2026-04-12 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('product', 'Product'), ('supply', 'Supply'), ('bundle', 'Bundle')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('is_activate', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bundle', serialize=False, to='inventory.item')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product', serialize=False, to='inventory.item')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supply', serialize=False, to='inventory.item')),
                ('entry_date', models.DateField()),
                ('is_sellable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=20)),
                ('reason', models.CharField(max_length=30)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_table', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='BundleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundles', to='inventory.item')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.bundle')),
            ],
        ),
    ]
